import Head from "next/head";

import type { ReactNode } from "react";
import type { NextPageWithLayout } from "@/types";

import { BlogsMain, Layout } from "@/components";

const BlogsPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Blogs Management | Operation Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BlogsMain />
      </main>
    </>
  );
};

BlogsPage.getLayout = (page: ReactNode) => {
  return <Layout>{page}</Layout>;
};

export default BlogsPage;
